In [ ]:
import numpy as np
import tensorflow as tf
import tensorflow_hub as hub
import tensorflow_text as text

In [ ]:
# This is our bert pre-trained preprocessing model
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/2"

# This is the bert base model
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/3"

# Load pre-trained pre-processing model
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [ ]:
my_text = ['My name is Darshan Hassan', 'I like to solve Problems', 'I have experience in Deep Learning']

text_preprocess = bert_preprocess_model(my_text) # perform preprocessing on text

In [ ]:
text_preprocess.keys()

dict_keys(['input_type_ids', 'input_mask', 'input_word_ids'])

In [ ]:
text_preprocess['input_type_ids']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0

In [ ]:
text_preprocess['input_word_ids']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[  101,  2026,  2171,  2003, 18243,  9688, 13222,   102,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0,     0,
            0,     0,     0, 

In [ ]:
text_preprocess['input_mask']

<tf.Tensor: shape=(3, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0

In [ ]:
# Load pre-trained Bert model
bert_model = hub.KerasLayer(encoder_url) # encoder model

In [ ]:
# converts text into vector
bert_result = bert_model(text_preprocess)

In [ ]:
bert_result.keys()

dict_keys(['pooled_output', 'sequence_output', 'encoder_outputs', 'default'])

In [ ]:
bert_result['default']

<tf.Tensor: shape=(3, 768), dtype=float32, numpy=
array([[-0.8533264 , -0.41499585, -0.27559367, ..., -0.62095135,
        -0.678719  ,  0.87546104],
       [-0.8932331 , -0.42591202, -0.48248816, ..., -0.49596497,
        -0.6531732 ,  0.93666327],
       [-0.6800903 , -0.1785232 ,  0.5481249 , ...,  0.19111787,
        -0.50313944,  0.7570601 ]], dtype=float32)>

In [ ]:
bert_result['sequence_output']

<tf.Tensor: shape=(3, 128, 768), dtype=float32, numpy=
array([[[ 0.07804468,  0.59615237, -0.18510836, ..., -0.09871033,
          0.1979618 ,  0.5323227 ],
        [ 0.08369936, -0.07439604, -0.64211315, ..., -0.20235153,
          0.23019788,  0.25895095],
        [-0.30311632,  0.06309082, -0.00286157, ..., -0.48661965,
          0.13205141,  0.22446743],
        ...,
        [-0.02497712,  0.3230483 ,  0.44137618, ...,  0.41565987,
          0.17092532, -0.05417432],
        [ 0.05169919,  0.30489486,  0.45454693, ...,  0.3208011 ,
          0.13130748,  0.03248415],
        [-0.03723863,  0.39989445,  0.46100733, ...,  0.3121304 ,
          0.11341842, -0.04067009]],

       [[ 0.12074251,  0.38999557, -0.33004415, ..., -0.20062983,
          0.08178762,  0.5237412 ],
        [ 0.78360933,  0.09641342, -0.5461166 , ..., -0.1109393 ,
          0.47805032,  0.09051526],
        [ 0.77308595,  0.71717125,  0.6045433 , ...,  0.31787714,
         -0.05617395,  0.1264247 ],
        ...,

In [ ]:
bert_result['pooled_output']

<tf.Tensor: shape=(3, 768), dtype=float32, numpy=
array([[-0.8533264 , -0.41499585, -0.27559367, ..., -0.62095135,
        -0.678719  ,  0.87546104],
       [-0.8932331 , -0.42591202, -0.48248816, ..., -0.49596497,
        -0.6531732 ,  0.93666327],
       [-0.6800903 , -0.1785232 ,  0.5481249 , ...,  0.19111787,
        -0.50313944,  0.7570601 ]], dtype=float32)>

In [ ]:
len(bert_result['encoder_outputs'])

12